### ISSUE TITLE
admin_review: Cannot install this package with Python 2.7 on OSX

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/geomag-imp#5]
I didn't intend to try an install with Python 2.7, but that's what I got when I created a test environment for some reason. At any rate, two issues:
1) You should probably stop supporting Python 2.7, since it is no longer being supported by anyone else
2) The install of geomag-algorithms didn't work. Errors below:

ERROR: Command errored out with exit status 1:
     command: /Users/mhearne/miniconda/envs/geomag/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4t/g5lgxtd57g71_cwqzrpmxcpw5848gj/T/pip-req-build-gnL3CM/setup.py'"'"'; __file__='"'"'/private/var/folders/4t/g5lgxtd57g71_cwqzrpmxcpw5848gj/T/pip-req-build-gnL3CM/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/4t/g5lgxtd57g71_cwqzrpmxcpw5848gj/T/pip-req-build-gnL3CM/pip-egg-info
         cwd: /private/var/folders/4t/g5lgxtd57g71_cwqzrpmxcpw5848gj/T/pip-req-build-gnL3CM/
    Complete output (25 lines):
    DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
    DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4t/g5lgxtd57g71_cwqzrpmxcpw5848gj/T/pip-req-build-gnL3CM/setup.py", line 23, in <module>
        use_pipfile=True,
      File "/Users/mhearne/miniconda/envs/geomag/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Users/mhearne/miniconda/envs/geomag/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/mhearne/miniconda/envs/geomag/lib/python2.7/site-packages/setuptools/dist.py", line 448, in __init__
        k: v for k, v in attrs.items()
      File "/Users/mhearne/miniconda/envs/geomag/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/Users/mhearne/miniconda/envs/geomag/lib/python2.7/site-packages/setuptools/dist.py", line 740, in finalize_options
        ep.load()(self)
      File "/Users/mhearne/miniconda/envs/geomag/lib/python2.7/site-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/Users/mhearne/miniconda/envs/geomag/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
        return self.resolve()
      File "/Users/mhearne/miniconda/envs/geomag/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/private/var/folders/4t/g5lgxtd57g71_cwqzrpmxcpw5848gj/T/pip-req-build-gnL3CM/.eggs/setuptools_pipfile-0.3.0-py2.7.egg/setuptools_pipfile/keyword.py", line 1, in <module>
        from collections.abc import Mapping
    ImportError: No module named abc
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by erigler-usgs** [comment]
PR #2 included changes that broke Py2 compatibility, and now require Py3.
